export type Release = { version:string; date:string; title:string; summary:string; changes:string[]; tier:'foundation'|'product'|'intelligence'|'security' };
export const releases: Release[] = [
{version:'0.5.0',date:'2026-09-13',title:'Local Operator',summary:'A practical local-first task cockpit stages audited, bounded OpenClicky work packets without pretending that desktop control is already connected.',tier:'product',changes:['New localhost-only /operator workspace for inventory, verification, and source-review tasks','Private 0700 outbox plus 0600 packet files and hash-chained SQLite receipts','Actor-scoped idempotency prevents duplicate task packet staging','Static task policies prohibit credentials, installs, account actions, network changes, publishing, money movement, deployment, Git push, and edits','OpenClicky handoff is visible and manual until its actual installed integration is inspected','New API, regression coverage, built-app smoke coverage, setup runbook, and explicit local-only configuration flag']},
{version:'0.4.0',date:'2026-09-12',title:'Shared Brain and Safe Director',summary:'A unified memory and device architecture, a local Director with durable task receipts, and reviewed ECC workflows form the next Agentic OS foundation.',tier:'foundation',changes:['Opt-in read-only Director console with fixed status and next-action operations','Durable local task IDs, idempotency, lifecycle and integrity-checked receipts','Administrator and same-origin API boundaries with zero inference or workload tools','Pinned curated ECC skills, completion loops, Agent-Reach and OpenClicky activation contracts','Obsidian workspace and Graphify index architecture with a shared cross-device identity roadmap','38 regression tests, built-app checks and Node 24 verification passed in GitHub CI','Checkout remains blocked until trusted server-side approval exists','Seeded dashboards remain visibly labeled; live memory, device and worker integrations are still pending']},
{version:'0.3.1',date:'2026-09-12',title:'Verification Baseline',summary:'NEO-CORTEX gains reproducible verification, policy regression tests, deterministic model selection, CI, and hardened checkout.',tier:'security',changes:['One-command secret scan, demo-boundary check, typecheck, tests, build and dependency audit','Core policy, safety, and model-routing regression tests','Deterministic model tier preferences replace catalog first-match behavior','Build gate prevents unlabeled seeded demo telemetry','Authenticated and policy-gated Stripe Checkout boundary','Least-privilege CI workflow with commit-pinned actions','Persistent state, decision and next-action records','Reproducible npm lockfile and Next.js 16 TypeScript configuration']},
{version:'0.3.0',date:'2026-09-06',title:'MACH1 Product Surface',summary:'NEO-CORTEX becomes a product-shaped Agentic OS with customer and operator experiences.',tier:'product',changes:['Next-generation public product site and pricing','Customer Mission Control dashboard','Founder backoffice for revenue, CRM and product health','Stripe subscription checkout integration boundary','Clerk authentication integration boundary','Upgrade timeline that is updated with shipped releases']},
{version:'0.2.0',date:'2026-09-06',title:'Control & Trust Foundation',summary:'The P0 safety boundary moved from design notes into typed runtime contracts.',tier:'security',changes:['Data classification and provider-aware routing','Intent Gateway contract','Deterministic Policy Kernel','Task/correlation IDs and execution receipts','Budgets, circuit breakers and kill switch','Secret lease and sandbox contracts','Checkpoint/resume interface']},
{version:'0.1.0',date:'2026-09-05',title:'Evolution Engine Seed',summary:'Initial governed self-improvement control plane.',tier:'foundation',changes:['Discovery → quarantine → evaluation → approval pipeline','Model router starter','Agent contract and small council','Social intelligence policy','Evolution source watchlist']}
];
